[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
indexmap = "2.0.0"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = { git = "https://github.com/GnomedDev/thin-vec", branch = "outline-capacity-overflow" }
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
rustc_macros = { path = "../rustc_macros" }
tempfile = "3.2"
# tidy-alphabetical-end
